# Generated by Django 6.1 on 2026-09-14 12:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTFWriteup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('web', 'Web Exploitation'), ('crypto', 'Cryptography'), ('pwn', 'Binary Exploitation'), ('rev', 'Reverse Engineering'), ('foren', 'Forensics')], default='web', max_length=20)),
                ('content', models.TextField()),
                ('date_published', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
