# Generated by Django 6.1 on 2026-09-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ctfwriteup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctfwriteup',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ctfwriteup',
            name='content',
        ),
        migrations.AddField(
            model_name='ctfwriteup',
            name='pdf_filename',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
