# Generated by Django 6.1 on 2026-09-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_ctfwriteup_category_remove_ctfwriteup_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctfwriteup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
