# Generated by Django 6.1 on 2026-09-14 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ctfwriteup_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctfwriteup',
            name='date_published',
        ),
    ]
