# Generated by Django 6.1 on 2026-09-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_ctfwriteup_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctfwriteup',
            name='writeup_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
