# Generated by Django 6.1 on 2026-09-21 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_ctfwriteup_writeup_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctfwriteup',
            name='pdf_filename',
        ),
    ]
