# Generated by Django 6.1 on 2026-09-28 05:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_ctfwriteup_starred_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctfwriteup',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_writeup', to=settings.AUTH_USER_MODEL),
        ),
    ]
